### ISSUE TITLE
Add Focus views extensions in the project

### ISSUE THREAD

**Issue by sebez** [KleeGroup/focus-starter-kit#13]
(Following discussion from https://github.com/KleeGroup/focus/issues/58)

On our project, we added our own extensions of Focus views.

An extension matches with a projet-level defined page pattern like *Composite detail with global load and save*.

This allows :
  * to encapsule project-specific patterns implementation
  * to reduce code duplication in the views
  * to have project-specific well named views to extend
  * to gain robustness when a new Focus release is shipped with breaking changes

This strategy could be encouraged on the other Focus projets for the previous reasons.

We store the views extensions at the application level : 

![pagetemplates](https://cloud.githubusercontent.com/assets/9380855/5778809/3ab9f72e-9d9e-11e4-8d89-160a2b6517dc.PNG)

**Comment by obtl** [comment]
thx. this method is already used in other projects. but , in general, we have less patterns to overload.

**Comment by obtl** [comment]
i closed this issue because i think this method has to be integrated in the focus documentation. this is not a focus issue.
