### ISSUE TITLE
Add DEFAULT_ROLE in initializer

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-starter-kit#15]
The file 'user-initializer.js' is not loaded at startup. This behavior prevents the user to have the default role. An 'application.noRights' notification is then displayed.

Please add the folowing line in 'app/initializer/index.js'
```
require('./user-initializer');
```

**Comment by Bernardstanislas** [comment]
Solved in 5eac596b801c1a73701dc25c12ea2840ffea54b0
